### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by TrySound**
Fixed breaking change.

### CODE REVIEW

**Comment by TrySound** [comment]
Something wrong with new jscs

**Comment by MoOx** [comment]
Can you be clear about what is this fixing please ? Thanks.

**Comment by TrySound** [comment]
There is a new balanced match version with some breaking change. It bacame more smarty and need to check start of parenthesis.

**Comment by TrySound** [comment]
jscs has some breaking too.

**Comment by TrySound** [comment]
validateJSDoc rule was deprecated and removed from jscs

**Comment by TrySound** [comment]
Do you want to replace this rule with something?

**Comment by MoOx** [comment]
I will remove jscs and use eslint next time I will work on this.

**Pull request merged**
