### PR TITLE
Promises

### PR DESCRIPTION
**Pull request by borodean**
Implements https://github.com/MoOx/reduce-function-call/issues/1

### CODE REVIEW

**Comment by borodean** [comment]
README has to be updated, but I’m not sure how to do it best.

@MoOx what do you think of it?

**Comment by MoOx** [comment]
Thanks for this PR.
I will try to make a deep review soon.
Maybe @ben-eb can be interested.

**Comment by ben-eb** [comment]
Looks good. :+1:

My original use case from #1 was solved already with postcss-value-parser - https://github.com/ben-eb/postcss-svgo - as I didn't need the recursion.

**Comment by MoOx** [comment]
@borodean maybe we should make another package? like async-reduce-function-call ?
I am thinking that sync can still be relevant. What do you think ?

**Comment by borodean** [comment]
@MoOx I guess in a case with an another package there would lots of similar code between both packages. It would make it harder to maintain. However, I do understand that the sync operation could be relevant.

**Comment by borodean** [comment]
Maybe the syntax of the current package should be extended to allow both sync and async calls, but I'm not sure in which particular way.

**Comment by MoOx** [comment]
Yeah, that's also a possibility.

**Comment by ben-eb** [comment]
`reduceFunctionCall.sync`?

**Comment by MoOx** [comment]
Why not :)

**Comment by MoOx** [comment]
Bump for the sync version.

**Comment by MoOx** [comment]
@borodean are you still interested by this, years later? 😅

**Comment by borodean** [comment]
@MoOx yup, I am :)

**Comment by MoOx** [comment]
So could we keep a sync thing & offer an async alternative too?

**Comment by borodean** [comment]
>So could we keep a sync thing & offer an async alternative too?

I don't know, you're the maintainer :)

How do you want to proceed with this?

If you want the sync version to be kept along with the async one, do you want me to take care of that?

**Comment by MoOx** [comment]
@borodean yeah that would be great. I am open for this. I don't really use this package anymore but since it's used a lot on npm, I don't want to let it rot :)
So if we could have a non breaking change that would bring the promise way to got, that would be awesome. Do you think you can handle it?

**Comment by borodean** [comment]
@MoOx sure, I will take a look 👍

**Pull request closed without merging**
